apiVersion: batch/v1
kind: Job
metadata:
  name: operator-cleanup-job
  labels:
    app: noname-remote-operator
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      serviceAccountName: noname-remote-operator-sa
      restartPolicy: Never
      containers:
        - name: remote-operator-cleanup
          image: {{ printf "%s:%s" .Values.nonameRemoteOperator.image.repository .Values.nonameRemoteOperator.image.tag | quote }}
          command: ["npm", "run", "cleanup"]
          env:
            - name: NOMANAGE_CLIENT_INSIDE_CONTAINER
              value: {{ quote .Values.nonameRemoteOperator.env.nomanageClientInsideContainer }}
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
        - name: noname-artifactory-credentials
