{{- if .Values.imageCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: noname-artifactory-credentials
  namespace: {{- toYaml .Release.Namespace | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecrets" . }}
{{- end }}
