apiVersion: v1
kind: ServiceAccount
metadata:
  name: noname-remote-operator-sa
  namespace: {{- toYaml .Release.Namespace | nindent 4 }}
  labels:
  {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.nonameRemoteOperator.serviceAccount.annotations | nindent 4 }}
