apiVersion: v1
kind: Namespace
metadata:
  name: cortex-xdr
  labels:
    app.kubernetes.io/name: cortex-xdr
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
---

apiVersion: v1
kind: Secret
metadata:
  name: xdr-agent-deployment
  namespace: cortex-xdr
type: Opaque
stringData:
  distribution-id: "a3ae6a00c43441d4b5e5cbdd009c4ee8"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: xdr-agent-user
  namespace: cortex-xdr

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xdr-agent-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xdr-agent-role-binding-cortex-xdr
subjects:
- kind: ServiceAccount
  name: xdr-agent-user
  namespace: cortex-xdr
roleRef:
  kind: ClusterRole
  name: xdr-agent-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: cortex-docker-secret
  namespace: cortex-xdr
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9hc2lhLXNvdXRoMS1kb2NrZXIucGtnLmRldiI6IHsidXNlcm5hbWUiOiAiX2pzb25fa2V5IiwgInBhc3N3b3JkIjogIntcbiAgXCJ0eXBlXCI6IFwic2VydmljZV9hY2NvdW50XCIsXG4gIFwicHJvamVjdF9pZFwiOiBcInhkci1pbi0zMzA0ODI5OTQ5OTQxXCIsXG4gIFwicHJpdmF0ZV9rZXlfaWRcIjogXCJkZDI2YzE0YWMxZDg5N2U2MGY1YzJjMzNmMDdkNjhlYmI0OTQ2OTAyXCIsXG4gIFwicHJpdmF0ZV9rZXlcIjogXCItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUM2VUdKNlFlYlZ4MnE3XFxuOEV5YnRwMTVXaDdabWFidG5sbW1SeWNCR1BoS3hnV1E4QTQ1Wi9VbW55UDVjV1FWRmhzOVViVGRxeTBNZjdUTVxcblNVVDBMTFZ5MjBDcTh0Z1VkWko4aGh3SzFyZG9UL3FYZkd3Wk9xVWZyRVNlZjIwRS84OVQxakFremNlSmkyTEdcXG5VQVJuSFVhSXZqYjhZYzcrTDFRZkMyY21TdkRwWTF6S2MzWnd2ZUxZOVE4RkswUkZ4Y1FqSkR2cGFEaHlHblZMXFxuN2t6SWlWZlR4OVhjRVQrU3RzWktXYlo3aG02bkRzZFQrR001SzFGbXpGQzNjamtnR3k0d3hmYkRQRW1Sczl5ZlxcbmdxOS9sTDBBVkZHUktCcm4ySlhZRDVUdUV4dklnbGpjQTdnRmNuMThMN1JvT1JrbHY0VW4xeVpSM1g5NWgyc2FcXG4zWEdROEI0ckFnTUJBQUVDZ2dFQU9QT1RkcTJvWXhhbkVMWGVwUWFJVW16eTJ5ODFzSkxqOG9qemFrbDR0RnFkXFxubnZWU1U4ZnNUeGI4UnlhYklqcjBycVRJTmE0NmdnU1RmcEt6Q2pTVWJueUk0dmlDaHBaOTVhU1U4OWM0anlGTFxcbmgzellDa283NlZlZVRoakRlWEM4cm5MZG1wSndlU0hyV3BWaEV5Z0d4SXZvZ1BOZzg2QUNCYzlWZzRZSzZEd2FcXG5nam5QTHhpVVFjVzFyaVBRWkROV2Zmc0RKL1hNS21jY0lWd0RRSHdTVDhLN21FR2NGT1ZwcnBnQUVxcHpzbkF1XFxudnNOK0RNSmhNNUNQWmRDaHpUV2RXaEtHS3NWcWtEU1k1N3lnUDBzL21CcFE3RGd6aGo3emFQU0pMeTgwTUlMb1xcbk5SZW5oTHZKUEQzc1ZJanlFU1hJbERMSjBBd2RvdGtWdVE3aXdoVjVnUUtCZ1FEbjRkeXNVYlV2ZmlzSXpuVDhcXG5QNGxIZ0g2VXhtRExER3dsQk5zZDUzZWdOMFJpZWVWVExDM3ZndEFrK0lRNG9ERExFRWlkbGlrWUxFeDM0cUJMXFxuN3QwckwxZjIzVHdnWUdUMktQS0Y4YVBzNklkNjBsekdnaW9PWFo2ZG1ZKzN2cEhpQVcza2g0Y1N0ZHJWN0dQOVxcbjRKSzRLK2IyU1AvWXhCOWxTeElwVHRjQndRS0JnUUROc1RiRGR2RnpoUHhOczIyTXZJU25QN3RaaCtUQnEreFBcXG5ZSXFlclBDY0V6RFJWWTVoY3V4N1NFYTJvRUM3ejRrMUxyQVV3clVxelVTdVhMa3hBeGVkNEpPaFpRUDloT1NkXFxuMlZ6b0F5NU9ja2FvOEZZbWVoSWg2YVRpbEt2VXpibE5JWFY1a3hDWFlyUi95VDViMTBQMXFON2ZQNWxOQTQyUFxcblV1S2JLdzRDNndLQmdRQ2ZWNkxYdXpJaGw3YWt6NUt1UUU3cWxvN2xWMGp1WHZQMW9GZWVQaEFEUmRjMVFJUm9cXG4yaVFhd1M2ZEtUVmE0Q0dIZVFJZFlER1BEZW5pUEJaZzk1eDk3NE9uL1RFekltcGVpWmJXbWsxR0lDZnhLNXRiXFxuUWRqNmxEVEtJZHNUcmQzN2kzWGpvNG9iUG1KSnZLNmRwL1BLb1VpT0YyM1FuRHppMDJxQWZrL2JRUUtCZ0JOL1xcbkxMV3lYSWlhbmwrdkZqODB6MDRiR0dNUUluckpGUWtoR1lLWTJlV3hXL3M3cE5kUDBXS09JMFhFUXQ2S2VYTDFcXG5EZk9wMFFwUmtxVUVYUGxzVlp5OVlNRDNsajA5ajMzMjBIdWRjWkkxK3NTZ28wbmFZRVdlbytabU9UTmVuS1hXXFxuK2crZ0JQNlVlSTkwUDlqc3VxQmFkV1dyM1pnVE1pUFhzMnNKMWJZcEFvR0JBS3BoM1g5WjQ5SFBkMldibVFPWlxcbnpWQ01oYmtEazNhYjdjVGxmSHdNRk5nMTVEa0t3MzU3YVM0dUV0bk9iMVlrcmw5aXhKYWlyS3MrUkYwSnZnQ3JcXG5Ua3FnVkJQc0xFWlJFUExpcE1hdUg5MVdqcWpDRG1ESC9yRGpOOTdrT2U5YkNxbXRld3pZNjBlMjVVZFBRVWtIXFxuRnhtRVMvUGVoK1RXcEUrZGhBRUFSSWk3XFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxcblwiLFxuICBcImNsaWVudF9lbWFpbFwiOiBcInB1bGwtaW1hZ2VAeGRyLWluLTMzMDQ4Mjk5NDk5NDEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb21cIixcbiAgXCJjbGllbnRfaWRcIjogXCIxMDA1NDMxODY0NzQ3MDY4NDE5ODRcIixcbiAgXCJhdXRoX3VyaVwiOiBcImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoXCIsXG4gIFwidG9rZW5fdXJpXCI6IFwiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW5cIixcbiAgXCJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmxcIjogXCJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHNcIixcbiAgXCJjbGllbnRfeDUwOV9jZXJ0X3VybFwiOiBcImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvcHVsbC1pbWFnZSU0MHhkci1pbi0zMzA0ODI5OTQ5OTQxLmlhbS5nc2VydmljZWFjY291bnQuY29tXCIsXG4gIFwidW5pdmVyc2VfZG9tYWluXCI6IFwiZ29vZ2xlYXBpcy5jb21cIlxufVxuIiwgImVtYWlsIjogInB1bGwtaW1hZ2VAeGRyLWluLTMzMDQ4Mjk5NDk5NDEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCAiYXV0aCI6ICJYMnB6YjI1ZmEyVjVPbnNpZEhsd1pTSTZJQ0p6WlhKMmFXTmxYMkZqWTI5MWJuUWlMQ0FpY0hKdmFtVmpkRjlwWkNJNklDSjRaSEl0YVc0dE16TXdORGd5T1RrME9UazBNU0lzSUNKd2NtbDJZWFJsWDJ0bGVWOXBaQ0k2SUNKa1pESTJZekUwWVdNeFpEZzVOMlUyTUdZMVl6SmpNek5tTURka05qaGxZbUkwT1RRMk9UQXlJaXdnSW5CeWFYWmhkR1ZmYTJWNUlqb2dJaTB0TFMwdFFrVkhTVTRnVUZKSlZrRlVSU0JMUlZrdExTMHRMVnh1VFVsSlJYWm5TVUpCUkVGT1FtZHJjV2hyYVVjNWR6QkNRVkZGUmtGQlUwTkNTMmQzWjJkVGEwRm5SVUZCYjBsQ1FWRkRObFZIU2paUlpXSldlREp4TjF4dU9FVjVZblJ3TVRWWGFEZGFiV0ZpZEc1c2JXMVNlV05DUjFCb1MzaG5WMUU0UVRRMVdpOVZiVzU1VURWalYxRldSbWh6T1ZWaVZHUnhlVEJOWmpkVVRWeHVVMVZVTUV4TVZua3lNRU54T0hSblZXUmFTamhvYUhkTE1YSmtiMVF2Y1ZobVIzZGFUM0ZWWm5KRlUyVm1NakJGTHpnNVZERnFRV3Q2WTJWS2FUSk1SMXh1VlVGU2JraFZZVWwyYW1JNFdXTTNLMHd4VVdaRE1tTnRVM1pFY0ZreGVrdGpNMXAzZG1WTVdUbFJPRVpMTUZKR2VHTlJha3BFZG5CaFJHaDVSMjVXVEZ4dU4ydDZTV2xXWmxSNE9WaGpSVlFyVTNSeldrdFhZbG8zYUcwMmJrUnpaRlFyUjAwMVN6RkdiWHBHUXpOamFtdG5SM2swZDNobVlrUlFSVzFTY3psNVpseHVaM0U1TDJ4TU1FRldSa2RTUzBKeWJqSktXRmxFTlZSMVJYaDJTV2RzYW1OQk4yZEdZMjR4T0V3M1VtOVBVbXRzZGpSVmJqRjVXbEl6V0RrMWFESnpZVnh1TTFoSFVUaENOSEpCWjAxQ1FVRkZRMmRuUlVGUFVFOVVaSEV5YjFsNFlXNUZURmhsY0ZGaFNWVnRlbmt5ZVRneGMwcE1hamh2YW5waGEydzBkRVp4WkZ4dWJuWldVMVU0Wm5OVWVHSTRVbmxoWWtscWNqQnljVlJKVG1FME5tZG5VMVJtY0V0NlEycFRWV0p1ZVVrMGRtbERhSEJhT1RWaFUxVTRPV00wYW5sR1RGeHVhRE42V1VOcmJ6YzJWbVZsVkdocVJHVllRemh5Ymt4a2JYQktkMlZUU0hKWGNGWm9SWGxuUjNoSmRtOW5VRTVuT0RaQlEwSmpPVlpuTkZsTE5rUjNZVnh1WjJwdVVFeDRhVlZSWTFjeGNtbFFVVnBFVGxkbVpuTkVTaTlZVFV0dFkyTkpWbmRFVVVoM1UxUTRTemR0UlVkalJrOVdjSEp3WjBGRmNYQjZjMjVCZFZ4dWRuTk9LMFJOU21oTk5VTlFXbVJEYUhwVVYyUlhhRXRIUzNOV2NXdEVVMWsxTjNsblVEQnpMMjFDY0ZFM1JHZDZhR28zZW1GUVUwcE1lVGd3VFVsTWIxeHVUbEpsYm1oTWRrcFFSRE56VmtscWVVVlRXRWxzUkV4S01FRjNaRzkwYTFaMVVUZHBkMmhXTldkUlMwSm5VVVJ1TkdSNWMxVmlWWFptYVhOSmVtNVVPRnh1VURSc1NHZElObFY0YlVSTVJFZDNiRUpPYzJRMU0yVm5UakJTYVdWbFZsUk1Rek4yWjNSQmF5dEpVVFJ2UkVSTVJVVnBaR3hwYTFsTVJYZ3pOSEZDVEZ4dU4zUXdja3d4WmpJelZIZG5XVWRVTWt0UVMwWTRZVkJ6Tmtsa05qQnNla2RuYVc5UFdGbzJaRzFaS3pOMmNFaHBRVmN6YTJnMFkxTjBaSEpXTjBkUU9WeHVORXBMTkVzcllqSlRVQzlaZUVJNWJGTjRTWEJVZEdOQ2QxRkxRbWRSUkU1elZHSkVaSFpHZW1oUWVFNXpNakpOZGtsVGJsQTNkRnBvSzFSQ2NTdDRVRnh1V1VseFpYSlFRMk5GZWtSU1ZsazFhR04xZURkVFJXRXliMFZETjNvMGF6Rk1ja0ZWZDNKVmNYcFZVM1ZZVEd0NFFYaGxaRFJLVDJoYVVWQTVhRTlUWkZ4dU1sWjZiMEY1TlU5amEyRnZPRVpaYldWb1NXZzJZVlJwYkV0MlZYcGliRTVKV0ZZMWEzaERXRmx5VWk5NVZEVmlNVEJRTVhGT04yWlFOV3hPUVRReVVGeHVWWFZMWWt0M05FTTJkMHRDWjFGRFpsWTJURmgxZWtsb2JEZGhhM28xUzNWUlJUZHhiRzgzYkZZd2FuVllkbEF4YjBabFpWQm9RVVJTWkdNeFVVbFNiMXh1TW1sUllYZFRObVJMVkZaaE5FTkhTR1ZSU1dSWlJFZFFSR1Z1YVZCQ1dtYzVOWGc1TnpSUGJpOVVSWHBKYlhCbGFWcGlWMjFyTVVkSlEyWjRTelYwWWx4dVVXUnFObXhFVkV0SlpITlVjbVF6TjJreldHcHZORzlpVUcxS1NuWkxObVJ3TDFCTGIxVnBUMFl5TTFGdVJIcHBNREp4UVdackwySlJVVXRDWjBKT0wxeHVURXhYZVZoSmFXRnViQ3QyUm1vNE1Ib3dOR0pIUjAxUlNXNXlTa1pSYTJoSFdVdFpNbVZYZUZjdmN6ZHdUbVJRTUZkTFQwa3dXRVZSZERaTFpWaE1NVnh1UkdaUGNEQlJjRkpyY1ZWRldGQnNjMVphZVRsWlRVUXpiR293T1dvek16SXdTSFZrWTFwSk1TdHpVMmR2TUc1aFdVVlhaVzhyV20xUFZFNWxia3RZVjF4dUsyY3JaMEpRTmxWbFNUa3dVRGxxYzNWeFFtRmtWMWR5TTFwblZFMXBVRmh6TW5OS01XSlpjRUZ2UjBKQlMzQm9NMWc1V2pRNVNGQmtNbGRpYlZGUFdseHVlbFpEVFdoaWEwUnJNMkZpTjJOVWJHWklkMDFHVG1jeE5VUnJTM2N6TlRkaFV6UjFSWFJ1VDJJeFdXdHliRGxwZUVwaGFYSkxjeXRTUmpCS2RtZERjbHh1Vkd0eFoxWkNVSE5NUlZwU1JWQk1hWEJOWVhWSU9URlhhbkZxUTBSdFJFZ3Zja1JxVGprM2EwOWxPV0pEY1cxMFpYZDZXVFl3WlRJMVZXUlFVVlZyU0Z4dVJuaHRSVk12VUdWb0sxUlhjRVVyWkdoQlJVRlNTV2szWEc0dExTMHRMVVZPUkNCUVVrbFdRVlJGSUV0RldTMHRMUzB0WEc0aUxDQWlZMnhwWlc1MFgyVnRZV2xzSWpvZ0luQjFiR3d0YVcxaFoyVkFlR1J5TFdsdUxUTXpNRFE0TWprNU5EazVOREV1YVdGdExtZHpaWEoyYVdObFlXTmpiM1Z1ZEM1amIyMGlMQ0FpWTJ4cFpXNTBYMmxrSWpvZ0lqRXdNRFUwTXpFNE5qUTNORGN3TmpnME1UazROQ0lzSUNKaGRYUm9YM1Z5YVNJNklDSm9kSFJ3Y3pvdkwyRmpZMjkxYm5SekxtZHZiMmRzWlM1amIyMHZieTl2WVhWMGFESXZZWFYwYUNJc0lDSjBiMnRsYmw5MWNta2lPaUFpYUhSMGNITTZMeTl2WVhWMGFESXVaMjl2WjJ4bFlYQnBjeTVqYjIwdmRHOXJaVzRpTENBaVlYVjBhRjl3Y205MmFXUmxjbDk0TlRBNVgyTmxjblJmZFhKc0lqb2dJbWgwZEhCek9pOHZkM2QzTG1kdmIyZHNaV0Z3YVhNdVkyOXRMMjloZFhSb01pOTJNUzlqWlhKMGN5SXNJQ0pqYkdsbGJuUmZlRFV3T1Y5alpYSjBYM1Z5YkNJNklDSm9kSFJ3Y3pvdkwzZDNkeTVuYjI5bmJHVmhjR2x6TG1OdmJTOXliMkp2ZEM5Mk1TOXRaWFJoWkdGMFlTOTROVEE1TDNCMWJHd3RhVzFoWjJVbE5EQjRaSEl0YVc0dE16TXdORGd5T1RrME9UazBNUzVwWVcwdVozTmxjblpwWTJWaFkyTnZkVzUwTG1OdmJTSXNJQ0oxYm1sMlpYSnpaVjlrYjIxaGFXNGlPaUFpWjI5dloyeGxZWEJwY3k1amIyMGlmUT09In19fQ==

---



---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cortex-agent
  namespace: cortex-xdr
  labels:

    app.kubernetes.io/name: cortex-agent
    app.kubernetes.io/part-of: cortex
    app.kubernetes.io/component: agent
    app.kubernetes.io/version: "9.0.0.141085"

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cortex-agent

  updateStrategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app.kubernetes.io/name: cortex-agent
      annotations:

        container.apparmor.security.beta.kubernetes.io/cortex-agent: unconfined

    spec:
      serviceAccountName: xdr-agent-user

      nodeSelector:
        kubernetes.io/os: linux

      hostNetwork: true
      hostPID: true
      hostIPC: true
      
      tolerations:

      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: PreferNoSchedule
      - operator: Exists
        effect: NoExecute

      containers:
      - name: cortex-agent
        
        image: asia-south1-docker.pkg.dev/xdr-in-3304829949941/agent-docker/cortex-agent:9.0.0.141085

        securityContext:
          appArmorProfile:
            type: Unconfined
          capabilities:
            add:
            - SYS_ADMIN
            - SYSLOG
            - SYS_CHROOT
            - SYS_MODULE
            - SYS_PTRACE
            - SYS_RESOURCE
            - SYS_RAWIO
            - DAC_OVERRIDE
            - DAC_READ_SEARCH
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - FOWNER
            - KILL
            - SETGID
            - SETUID

        env:
        - name: XDR_HOST_ROOT
          value: "/host-fs"
        - name: XDR_POD_INFO
          value: "/var/run/pod-info"
        - name: XDR_CLUSTER_NAME_URL
          value: "metadata2"
        - name: XDR_CLUSTER_NAME
          value: ""
        - name: XDR_VAR_LOG_HOST_PATH
          value: "/var/log"
        - name: XDR_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        

        volumeMounts:

        - name: host-fs
          mountPath: /host-fs
          readOnly: true

        - name: var-log
          mountPath: /var/log

        - name: host-km-directory
          mountPath: /lib/modules

        - name: pod-info
          mountPath: /var/run/pod-info
          readOnly: true

        - name: agent-ids
          mountPath: /etc/traps

        - name: deployment-secrets
          mountPath: /opt/traps/config/deployment
          readOnly: true

        resources:
          requests:
            cpu: "200m"
            memory: "600Mi"
            
          limits:
            memory: "2Gi"
            

      terminationGracePeriodSeconds: 90

      volumes:
      - name: host-fs
        hostPath:
          path: /
          type: Directory

      - name: var-log
        hostPath:
          path: "/var/log"
          type: DirectoryOrCreate
      - name: host-km-directory
        hostPath:
          path: /lib/modules

      - name: pod-info
        downwardAPI:
          items:
          - path: uid
            fieldRef:
              fieldPath: metadata.uid
          - path: name
            fieldRef:
              fieldPath: metadata.name
          - path: labels
            fieldRef:
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              fieldPath: metadata.annotations
      - name: agent-ids
        hostPath:
            path: /etc/traps
            type: DirectoryOrCreate

      - name: deployment-secrets
        secret:
          secretName: xdr-agent-deployment
      
      imagePullSecrets:
      - name: cortex-docker-secret
