apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: my-vault
spec:
  address: "http://vault.vault.svc:8200"
  skipTLSVerify: true
  provider: 
    kubernetes:
      mount: kubernetes
      role: myapp-role
