apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  labels:
    app: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: vulnerable-app
        image: aniket0808/azure-devops:152
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        securityContext:
          runAsUser: 0
          privileged: true
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
        env:
        - name: ENVIRONMENT
          value: "test"
        - name: DEBUG
          value: "true"
