apiVersion: v1
kind: PersistentVolume
metadata:
  name: iq-server-pv
  namespace: sonatype
  labels:
   app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "iq"
    meta.helm.sh/release-namespace: "sonatype"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: "/mnt/data/iq-server"  # Update with a valid host path
