apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-cert
  namespace: monitoring
spec:
  secretName: monitoring-cert-tls
  dnsNames:
    - prometheus.secyour.space
    - grafana.secyour.space
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
